### ISSUE TITLE
unorderable types

### ISSUE THREAD

**Issue by yarolig** [Shyzuna/pyweek26#1]
I used python3.5. May be 3.6 will work better.

Traceback (most recent call last):
  File "main.py", line 5, in <module>
    gameManager.start()
  File "/home/ai0/pyjudge/unpacked/operation-moonlight/modules/gameManager.py", line 152, in start
    self._earth.sendEnergy(transmitter, batteriesList)
  File "/home/ai0/pyjudge/unpacked/operation-moonlight/objects/earth.py", line 34, in sendEnergy
    if leftToSend <= 0:
TypeError: unorderable types: NoneType() <= int()

It crashes sometimes when a contract becomes completed.

**Comment by Shyzuna** [comment]
Hey, I gave a try with python 3.5.2 (with pygame and numpy installed).
And it was working fine for me.
Let me know if it works on python 3.6 !
[Edited]
Never mind I got your error.
I'm looking for it !

**Comment by Shyzuna** [comment]
I think I fixed the problem.
In some conditions the battery when delivering energy could make crash the game.
Thanks for your attention and tell me if the crash still occurs !
